---
# tasks file for testo
 - name: We have two tasks in which to install webserver
   yum:
        name: httpd
        state: present

 - name: copy html file to /var/www/html
   copy:
         src: files/index.html
         dest: /var/www/html/
         owner: root
         group: root
         mode: 0644

 - name: restart the httpd
   service:
         name: httpd
         state: reloaded
...
